# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn build:all
      - run: (cd packages/rrweb-snapshot && npm publish --access public)
        env:
          NODE_AUTH_TOKEN: ${{secrets.SMARTESTING_NPM_TOKEN}}
      - run: (cd packages/types && npm publish --access public)
        env:
          NODE_AUTH_TOKEN: ${{secrets.SMARTESTING_NPM_TOKEN}}
      - run: (cd packages/rrdom && npm publish --access public)
        env:
          NODE_AUTH_TOKEN: ${{secrets.SMARTESTING_NPM_TOKEN}}
      - run: (cd packages/rrweb && npm publish --access public)
        env:
          NODE_AUTH_TOKEN: ${{secrets.SMARTESTING_NPM_TOKEN}}
